configfile:
  long_arg: '--configfile'
  helper: 'Load a configuration file'
  action: 'append'
configdump:
  long_arg: '--configdump'
  helper: 'Dump a configuration file'
  action: 'store_true'
fun:
  long_arg: '--fun'
  default: ''
  action: 'action.fun'
  helper: 'supress'
