#!/bin/bash
# Cluster protein sequences

#========================================================================
# Parameters
#========================================================================
[ -z ${RBASHPIPE_GI2CONTEXT_NAME} ] && gi2context_set_environment "$1"
mbclog=${RBASHPIPE_GI2CONTEXT_LOG}/${RBASHPIPE_GI2CONTEXT_NAME}.mblastclust.log

#========================================================================
# Start
#========================================================================
printlog -t START ${RBASHPIPE_GI2CONTEXT_POST} $minseqlen

safe_remove ${RBASHPIPE_GI2CONTEXT_POST}.sim ${RBASHPIPE_GI2CONTEXT_FASTA}.sim error.log ${mbclog}
cutoff=$(seq -f '-s %.1f' 0.1 0.1 1.0)
mblastclust --nodelete -b ${RBASHPIPE_GI2CONTEXT_POST}.1 $cutoff ${RBASHPIPE_GI2CONTEXT_FASTA} 2>> ${mbclog} 1>&2
cutoff=$(seq -f '-s %g.0=0.0' 15 5 100)
mblastclust --nodelete -b ${RBASHPIPE_GI2CONTEXT_POST}.2 $cutoff ${RBASHPIPE_GI2CONTEXT_FASTA} 2>> ${mbclog} 1>&2
mblastclust --nodelete -b ${RBASHPIPE_GI2CONTEXT_POST}.3         ${RBASHPIPE_GI2CONTEXT_FASTA} 2>> ${mbclog} 1>&2
cutoff=$(seq -f '%g.0' 10 5 100 | xargs -n1 -I {} seq -f '-s {}=%.1f' 0 0.1 1)
mblastclust --nodelete -b ${RBASHPIPE_GI2CONTEXT_POST}.4 $cutoff ${RBASHPIPE_GI2CONTEXT_FASTA} 2>> ${mbclog} 1>&2
safe_remove ${RBASHPIPE_GI2CONTEXT_POST}.sim error.log ${RBASHPIPE_GI2CONTEXT_FASTA}.sim

#========================================================================
# End
#========================================================================
printlog -t END ${RBASHPIPE_GI2CONTEXT_POST} $minseqlen
unset minseqlen fasta
