#!/bin/bash

#========================================================================
# Parameters
#========================================================================
if [ -z "${RBASHPIPE_GI2CONTEXT_NAME}" ]; then gi2context_set_environment "$1"; fi

#========================================================================
# Start
#========================================================================
printlog -t START ${RBASHPIPE_GI2CONTEXT_POST}

# Initiaize table of properties with all GIs
properties=${RBASHPIPE_GI2CONTEXT_POST}.properties.tsv
if [ -s ${RBASHPIPE_GI2CONTEXT_DATA}.gi ] && [ -r ${RBASHPIPE_GI2CONTEXT_DATA}.gi ]; then
    (echo ID; sort -u ${RBASHPIPE_GI2CONTEXT_DATA}.gi) > $properties
else
    printlog -t START unable to read list of GIs from ${RBASHPIPE_GI2CONTEXT_POST}
    if [[ $_ != $0 ]]; then return 1; else exit 1; fi
fi

# Join tables of sequence properties
for suffix in pfam.arch profiledb.arch length defline tax
do
    target=${RBASHPIPE_GI2CONTEXT_POST}.${suffix}
    if [ ! -s $target ]; then continue; fi

    case "$target" in
	*.arch)
	    column=`echo $suffix | cut -f 1 -d .`
	    tjoin -rd -t left -i2 1 -sh2 ID -sh2 $column $properties $target > ${properties}.tmp
	    ;;

	*.defline)
	    tjoin -rd -t left -i2 description $properties $target > ${properties}.tmp
	    ;;

	*)
	    tjoin -rd -t left -x2 0 $properties $target > ${properties}.tmp
	    ;;
    esac
    if [ -r ${properties}.tmp ] && [ -s ${properties}.tmp ]; then mv ${properties}.tmp ${properties}; fi
done
unset cfile number suffix table target

#========================================================================
# End
#========================================================================
printlog -t END ${RBASHPIPE_GI2CONTEXT_POST}
unset cfile number suffix table target
