#!/bin/bash

#========================================================================
# Parameters
#========================================================================
[ -z "${RBASHPIPE_GI2CONTEXT_NAME}" ] && gi2context_set_environment "$1"
set +e # Required because grep and find may return error on execution

#========================================================================
# Start
#========================================================================
printlog -t START "${RBASHPIPE_GI2CONTEXT_POST} (${RBASHPIPE_GI2CONTEXT_NAME})"

# Other signatures
other=${RBASHPIPE_GI2CONTEXT_POST}.other.txt
find $RBASHPIPE_OUTPUT_DIR/post | grep "${RBASHPIPE_GI2CONTEXT_NAME}" \
    | grep -E "\.other.table$" > $other

# ProfileDB
profiledb=${RBASHPIPE_GI2CONTEXT_POST}.profiledb.txt
find $RBASHPIPE_OUTPUT_DIR/post | grep "${RBASHPIPE_GI2CONTEXT_NAME}" \
    | grep -E "\.srch2table$" | grep -v -i '/pfam' > $profiledb
if [ -s "$profiledb" ]; then
    cat $other >> $profiledb
    cat $profiledb | xargs cat | domain2architecture -e 0.0102 \
	> ${RBASHPIPE_GI2CONTEXT_POST}.profiledb.arch
fi

# Pfam
pfam=${RBASHPIPE_GI2CONTEXT_POST}.pfam.txt
find $RBASHPIPE_OUTPUT_DIR/post | grep "${RBASHPIPE_GI2CONTEXT_NAME}" \
    | grep -E "\.srch2table$" | grep -i '/pfam' > $pfam
if [ -s "$pfam" ]; then
    cat $other >> $pfam
    cat $pfam | xargs cat | domain2architecture -e 0.0102 \
        > ${RBASHPIPE_GI2CONTEXT_POST}.pfam.arch
fi

#========================================================================
# End
#========================================================================
printlog -t END "${RBASHPIPE_GI2CONTEXT_POST} (${RBASHPIPE_GI2CONTEXT_NAME})"
unset other pfam profiledb
set -e # Reset normal 'stop on first error' behaviour
