#!/bin/bash

# Merge neighborhood and sequence proerties, reformat as block

#========================================================================
# Parameters
#========================================================================
[ -z "${RBASHPIPE_GI2CONTEXT_NAME}" ] && gi2context_set_environment "$1"

#========================================================================
# Start
#========================================================================
printlog -t START ${RBASHPIPE_GI2CONTEXT_POST}

# Generate compact neighborhoods with domain architecture information
for lib in pfam profiledb
do
    tarch=${RBASHPIPE_GI2CONTEXT_POST}.${lib}.arch
    neigh=${RBASHPIPE_GI2CONTEXT_DATA}.neighborhood
    narch=${RBASHPIPE_GI2CONTEXT_POST}.neighborhood.${lib}.arch
    if  [ -s $neigh ] && [ -s $narch ] && [ -s $tarch ]; then
	neighborhood_explorer -y -o compact    -a ${narch} -a ${tarch} $neigh > ${tarch}.compact
	neighborhood_explorer -y -o compact -s -a ${narch} -a ${tarch} $neigh > ${tarch}.s.compact
	for number in 1 2 3
	do
	    cfile=$(select_from_dir -a RBASHPIPE_PIPELINE_DIR "clusters_to_blocks.${number}.conf")
	    if [ -z $cfile ] || [ ! -s $cfile ] || [ ! -r $cfile ]; then continue; fi
	    clusters=${RBASHPIPE_GI2CONTEXT_POST}.${number}.clusters
	    tjoin -t right -rd -x2 0 -i1 query -i1 neighborhood -i1 locus_tag -i1 nucleotide \
		  ${tarch}.compact   ${clusters}.arch.tsv > ${clusters}.${lib}.compact
	    table2blocks --configfile $cfile ${clusters}.${lib}.compact   > ${clusters}.${lib}.compact.curated
	    tjoin -t right -rd -x2 0 -i1 query -i1 neighborhood -i1 locus_tag -i1 nucleotide \
		  ${tarch}.s.compact ${clusters}.arch.tsv > ${clusters}.${lib}.s.compact
	    table2blocks --configfile $cfile ${clusters}.${lib}.s.compact > ${clusters}.${lib}.s.compact.curated
	done
    fi
done

#========================================================================
# End
#========================================================================
printlog -t END  ${RBASHPIPE_GI2CONTEXT_POST}
unset cfile clusters narch neigh tarch
