#!/bin/bash

#========================================================================
# Help message
#========================================================================
export minseqlen=5
function gi2context_process_fasta_help() {
    echo -n "Usage: rbashpipe [1] -i gi2context_process_fasta_help [2] [3] input.gi
Available options for his module:

  Option     : Description                                          : Default
 ------------:------------------------------------------------------:----------
  -l <int>   : set minimum length allowed length for sequences      : $minseqlen

Note:
You can set options, at the positions indicate between square brackets, for
[1] the rbashpipe system
[2] the gi2context pipeline (guaranteed to work if preceded by '--')
[3] this module  (guaranteed to work if preceded by a second '--')
"
}

#========================================================================
# Command line parser
#========================================================================
OPTERR=1
while getopts "l:h" opt
do
    case "$opt" in
	l)
	    export minseqlen="$OPTARG"
	    simplelog INFO "set minimum allowed length for sequences to ${minseqlen}"
	    ;;
	h)
	    gi2context_process_fasta_help "$RBASHPIPE_HELP_PAGE"
	    exit 1
	    ;;
	*)
	    gi2context_process_fasta_help "$RBASHPIPE_HELP_PAGE"
	    exit 1
	    ;;
    esac
done
unset opt
shift $((OPTIND-1))
OPTIND=0

#========================================================================
# Gi2context template: make sure a proper environment was set
#========================================================================
[ -z ${RBASHPIPE_GI2CONTEXT_NAME} ] && gi2context_set_environment "$@"

#========================================================================
# Start
#========================================================================
printlog -t START $minseqlen ${RBASHPIPE_GI2CONTEXT_FASTA} ${RBASHPIPE_GI2CONTEXT_POST}

# Parse FASTA: collect sequence statistics and descriptions
fasta2id ${RBASHPIPE_GI2CONTEXT_FASTA} > ${RBASHPIPE_GI2CONTEXT_POST}.ids
fasta2description ${RBASHPIPE_GI2CONTEXT_FASTA} > ${RBASHPIPE_GI2CONTEXT_POST}.defline
seqstats ${RBASHPIPE_GI2CONTEXT_FASTA} > ${RBASHPIPE_GI2CONTEXT_POST}.length

# Remove non-IUPAC residues (Phobius won't accept a J character)
perl -i -pe 's/J/X/g if !/^>/' ${RBASHPIPE_GI2CONTEXT_FASTA}

# Remove short sequences
filter_sequences -g $minseqlen

# Format sequences for BLAST
#makeblastdb -dbtype prot -title $RBASHPIPE_GI2CONTEXT_NAME -in ${RBASHPIPE_GI2CONTEXT_FASTA} -logfile $RBASHPIPE_OUTPUT_DIR/log/${RBASHPIPE_GI2CONTEXT_NAME}.makeblastdb.log

#========================================================================
# End
#========================================================================
printlog -t END $minseqlen ${RBASHPIPE_GI2CONTEXT_FASTA} ${RBASHPIPE_GI2CONTEXT_POST}
unset minseqlen
