#!/bin/bash
# Parse Genbank files

#========================================================================
# Parameters
#========================================================================
[ -z "${RBASHPIPE_GI2CONTEXT_NAME}" ] && gi2context_set_environment "$1"

#========================================================================
# Start
#========================================================================
printlog -t START "${RBASHPIPE_GI2CONTEXT_DATA}.gbk"

# Genbank to table
genbank="${RBASHPIPE_GI2CONTEXT_DATA}.gbk"
if [ -s "${genbank}" ] || [ -r "${genbank}.gbk" ]; then
    seq2taxonomy -y ${RBASHPIPE_GI2CONTEXT_DATA}.gbk | tjoin -rd -o 0 \
	| uniq > ${RBASHPIPE_GI2CONTEXT_POST}.gbk.tax
else
    printlog -t WARNING "Could not open Genbank file ${genbank}"
fi

#========================================================================
# End
#========================================================================
printlog -t END "${RBASHPIPE_GI2CONTEXT_DATA}.gbk"
unset genbank

