#!/bin/bash
# This is the gi2context pipeline

#========================================================================
# Process each input file
#========================================================================
for nextTarget in "$@"
do
    printlog -t INFO "processing target $nextTarget"

    # Initial target
    gi2context_set_environment "$nextTarget"   # Initialize environment
    prepare_analysis_directories "$nextTarget" # Create output directories and process input GI list using wp2ref
    source get_sequences   fasta genbank       # Download sequences
    seqid_to_data                              # Download more data (leaf names, taxonomy)
    source process_fasta -l 5                  # Download and cluster target sequences
    source process_genbank                     # Extract more data from genbank
    source cluster_sequences                   # Build clusters
    #source build_preliminary_phylogeny        # Create query alignment + phylogeny
    source splitseq                            # Break sequence file into pieces
    source detect_sequence_signatures_split    # Run Pfam profiles and TM/SP for all sequences
    source infer_architectures                 # Merge all information
    source collect_properties                  # Join data on each sequence to one table
    source table_to_curated                    # Join all data in one table, create input for curation

    # Neighbors
    get_neighborhood                           # Creates ${RBASHPIPE_GI2CONTEXT_NAME}.wp2ref.neighborhood
    gi2context_set_environment "${RBASHPIPE_GI2CONTEXT_NAME}.neighborhood"
    source get_sequences   fasta genbank       # Download sequences
    source process_fasta -l 5                  # Download and cluster target sequences
    source cluster_sequences                   # Build clusters
    source splitseq                            # Break sequence file into pieces
    source detect_sequence_signatures_split    # Run Pfam profiles and TM/SP for all sequences
    source infer_architectures                 # Merge all information
    source collect_properties                  # Join data on each sequence to one table
    source table_to_curated                    # create input for curation

    # Merge results
    gi2context_set_environment "$nextTarget"
    source parse_neighborhood                  # Create compact neighborhood files

    # Summarize target and neighbors
    cleanup_and_report_issues                  # Cleanup and summarize error logs
done
unset nextTarget
