#!/bin/bash

#========================================================================
# Parameters
#========================================================================
[ -z "${RBASHPIPE_GI2CONTEXT_NAME}" ] && gi2context_set_environment "$1"

#========================================================================
# Start
#========================================================================
printlog -t START ${RBASHPIPE_GI2CONTEXT_POST}

# Initiaize table of properties with all GIs
properties=${RBASHPIPE_GI2CONTEXT_POST}.properties.tsv
if [ ! -s ${properties} ] ||  [ ! -r ${properties} ]; then
    printlog -t ERROR "Unable to read table of sequence properties ${properties}"
    if [[ $_ != $0 ]]; then return 1; else exit 1; fi
fi

# Load block builder routines
rules=$(select_from_dir -a RBASHPIPE_PIPELINE_DIR "block_rules.conf")
if [ ! -z $rules ] && [ -s "$rules" ] && [ -r $rules ]; then
    rules="--configfile $rules"
else
    printlog -t "unable to load configuration file block_rules.conf!"
    rules=""
fi

# Process clusters
for number in 1 2 3
do
    # Select input
    target=${RBASHPIPE_GI2CONTEXT_POST}.${number}.clusters
    if [ ! -s $target ]; then continue; fi

    # Join properties and clusters!
    table=${target}.arch.tsv # Ouput table
    tjoin -x2 0 -rd -t left $target $properties > $table

    # Reformat joined table as blocks
    cfile=$(select_from_dir -a RBASHPIPE_PIPELINE_DIR "clusters_to_blocks.${number}.conf")
    if echo "$target" | grep -q neighborhood 2> /dev/null; then
	cfile=$(select_from_dir -a RBASHPIPE_PIPELINE_DIR "clusters_to_blocks.neighborhood.${number}.conf")
    fi
    if [ ! -z $cfile ] && [ -s "$cfile" ] && [ -r $cfile ]; then
	printlog -t INFO "selected configuration file: $cfile"
	table2blocks ${rules} --configfile $cfile $table > ${target}.curated
    else
	printlog -t WARNING "unable to load configuration file $configfile!"
    fi
done

#========================================================================
# End
#========================================================================
printlog -t END ${RBASHPIPE_GI2CONTEXT_POST}
unset cfile number rules table target
