site_name: Rotifer tools
site_url: https://my.gitlab.io/mkdocs
# theme: 'material ' #Vreadthedocs

theme:
    name: 'material'

nav:
- Rotifer: 'index.md'
- Programs:
    - 'Rneighbors': 'programs/rneighbors.md'
    - 'acc2operon': 'programs/acc2operon.md'


- Modules:
   - Core:
     - Content: 'modules/core/index.md'
     - CLI: 'modules/core/cli.md'
     - Functions: 'modules/core/functions.md'
   - Tools:
     - Content: 'modules/tools/index.md'
     - Search:  'modules/tools/search.md'
     - Domain:  'modules/tools/domain.md'
   - Neighborhood:
     - Content: 'modules/neighborhood/index.md'
     - Neighborhood: 'modules/neighborhood/neighborhood.md'
# #   -'usage': 'mymodulesusage.md'




