# Environment variables for Rotifer
#
# WARNING:
#
#  YAML cares about IDENTATION therefore be aware
#  of how many invisible characters (white spaces)
#  are used at the start of a row
#
# Child process initiated by rotifer components will
# be able to access the values of environment variables
# set here

# YAML mandatory block header (don't change this row!)
---

# DATA: scalar
# Uncomment and set the path to your data
#ROTIFER_DATA: /panfs/pan1/proteinworld/data

# PATH: list (array)
# Where else should I search for installed programs?
#
# This block helps preventing failures caused by incomplete
# shells environments like those that may be set for cron
# jobs or remote sessions. 
#
# If your copy of Rotifer never fails, you don't need it.
#
#PATH:
# - /usr/local/bin
