#!/bin/bash

# Load environment
#source /etc/profile

# Directories
basedir=${ROTIFER_DATA:-/databases}
pdbdir=$basedir/pdb
dalidb=$basedir/dalidb
blastdb=$basedir/blast/dalidb
pdburl=rsync.rcsb.org::ftp_data/structures/divided/pdb/

# functions
dalimport () 
{ 
    s=${2:-${pdbdir:-${basedir:-/databases}/pdb}};
    t=${3:-${dalidb:-${basedir:-/databases}/dalidb}};
    c=$(echo $1 | cut -c 2-3);
    wd=/tmp/dalimport.$1.$(date +%s);
    pd=$(pwd);
    mkdir $wd;
    cd $wd;
    gunzip -c $s/$c/pdb${1}.ent.gz > pdb${1}.ent;
    import.pl --pdbfile pdb${1}.ent --pdbid $1 --dat $t;
    cd $pd;
    rm -fr $wd
}
export -f dalimport

# Run rsync
/usr/bin/rsync $TEST -rlpt -v -z --port=33444 --delete --prune-empty-dirs --delete-excluded $pdburl $pdbdir

# Update Dali database
find $pdbdir -name 'pdb*.ent.gz' | cut -c 22-25 > $dalidb/pdb.latest.txt
\ls $dalidb/ | grep dat | cut -c 1-5 > $dalidb/pdb.list
cut -c 1-4 $dalidb/pdb.list | sort -u | grep -vwFf - $dalidb/pdb.latest.txt | parallel -N1 -j36 dalimport
\ls $dalidb/ | grep dat | cut -c 1-5 > $dalidb/pdb.list
cat $dalidb/pdb.list | parallel -N100 -j36 --pipe "dat2fasta.pl $dalidb | awk -v RS='>' -v FS='\n' -v ORS='' '{ if (\$2) print \">\"\$0 }'" > $dalidb/pdb.fasta
makeblastdb -in $dalidb/pdb.fasta -out $blastdb -dbtype prot

# Finish
exit $?
