#!/bin/bash

# This script assumes data will be stored in a master data
# directory, with subdirectories corresponding to different
# sections of the data store and a directory for each data
# slot (target) under that section.
#
# root data directory => section => target
#
# Under this model, the path to the working directory of this
# script is $DATABASES (root) => fadb (section) => nr (target)
# i.e. $DATABASES/fadb/nr
#
# Additionally, the basename of most data files will match the
# target name. Therefore, the NR FASTA file, is
#
# $DATABASES/fadb/nr/nr
#
# The script performs atomic updates by storing each update
# within a versioned name (nr.$version), derived from the last
# run date, and updating the link $DATABASES/fadb/nr points to
# 

set -e # Abort at first error!

# Environment and parameters
dependencies="aria2c mmseqs esl-sfetch"
version=$(date +%Y%m%d)
section=fadb
target=nr
new=$target.$version
log=${new}.log

# Check for dependencies
for program in $dependencies
do
	if [ -z $(which $program) ]; then
		echo "Could not find mmseqs executable! Aborting..."
		exit 1
	fi
done

# Access data root directory
if [ ! -d $DATABASES ]; then
	echo "Data root directory not set!
Set the environment variable DATABASES to the root of the data directory.
Aborting..."
	exit 1
fi
cd $DATABASES

# Enter section
if [ ! -d $section ]; then
	echo "Creating directory for section $section at $DATABASES"
	mkdir $section
fi
cd $section

# Build new directory
if [ -d $new ]; then
	echo "Cleaning up target $new"
	rm -fr $new
fi
mkdir $new
cd $new

# Main block
{
	# Download and unpack
	echo "Downloading latest NR and taxonomy files to $new"
	mmseqs databases NR nrDB tmp
	mmseqs convert2fasta nrDB nr
	esl-sfetch --index nr

	echo "Using linclust to cluster NR database: 50% identity and 90% alignment coverage"
	mmseqs cluster nrDB nr50clu tmp2 --min-seq-id 0.5 -c 0.9 --cov-mode 0 --threads 20 --split-memory-limit 64G
	mmseqs createtsv nrDB nr50clu nr50clu.tsv
	mmseqs result2repseq nrDB nr50clu nr50rep -v 0
	mmseqs result2flat nrDB nrDB nr50rep nr50 --use-fasta-header  -v 0
	#mmseqs createsubdb nr50clu nrDB nr50DB
	#mmseqs convert2fasta nr50DB nr50
	esl-sfetch --index nr50
	if [ -f $DATABASES/taxonomy/accession2taxid/prot.accession2taxid.FULL ]; then
		makeblastdb -dbtype prot -in nr50 -parse_seqids \
		 -title "NCBI Protein database representatives for 50% indentity maximum" \
		 -taxid_map $DATABASES/taxonomy/accession2taxid/prot.accession2taxid.FULL
	else
		makeblastdb -dbtype prot -in nr50 -parse_seqids \
		 -title "NCBI Protein database representatives for 50% indentity maximum"
	fi

	# Update link
	cd $DATABASES/$section
	if [ -L $target ]; then
		rm -f $target
	fi
	ln -s $new $target
} > $log 2>&1

# Exit cleanly
exit $?
